/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TradingMode = IDL.Variant({
  'liveTrading' : IDL.Null,
  'shadowTrading' : IDL.Null,
  'paperTrading' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PromptTemplate = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'example' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const PositionType = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
});
export const Trade = IDL.Record({
  'owner' : IDL.Principal,
  'size' : IDL.Float64,
  'profitLoss' : IDL.Float64,
  'positionType' : PositionType,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Opt(IDL.Float64),
});
export const TradingStatus = IDL.Record({
  'mode' : TradingMode,
  'tradingEnabled' : IDL.Bool,
  'binanceConnected' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'tradingStatus' : TradingStatus,
});
export const CandleSummary = IDL.Record({
  'totalVolume' : IDL.Float64,
  'totalCount' : IDL.Int,
  'avgPrice' : IDL.Float64,
  'avgVolume' : IDL.Float64,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'time' : IDL.Int,
  'volume' : IDL.Float64,
});
export const Dataset = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'candles' : IDL.Vec(Candle),
  'uploadedAt' : IDL.Int,
});
export const HealthStatus = IDL.Variant({
  'healthy' : IDL.Null,
  'unreachable' : IDL.Null,
  'maintenance' : IDL.Null,
  'degraded' : IDL.Null,
  'appIssue' : IDL.Null,
});
export const AppHealth = IDL.Record({
  'status' : HealthStatus,
  'message' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBinanceAccount' : IDL.Func([IDL.Text, IDL.Text, TradingMode], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'disconnectBinance' : IDL.Func([], [], []),
  'filterPromptTemplates' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PromptTemplate)],
      ['query'],
    ),
  'getAllDatasetIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllPromptTemplates' : IDL.Func([], [IDL.Vec(PromptTemplate)], ['query']),
  'getAllTrades' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandleSummary' : IDL.Func([IDL.Text], [CandleSummary], ['query']),
  'getDataset' : IDL.Func([IDL.Text], [IDL.Opt(Dataset)], ['query']),
  'getHealthStatus' : IDL.Func([], [HealthStatus], ['query']),
  'getPromptTemplate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PromptTemplate)],
      ['query'],
    ),
  'getSystemHealth' : IDL.Func([], [AppHealth], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePromptTemplate' : IDL.Func([PromptTemplate], [], []),
  'saveTrade' : IDL.Func([IDL.Text, Trade], [], []),
  'setSystemHealth' : IDL.Func([HealthStatus], [], []),
  'updateTradingMode' : IDL.Func([TradingMode], [], []),
  'uploadDataset' : IDL.Func(
      [IDL.Text, IDL.Vec(Candle), IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'uploadFile' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'verifyBinanceConnection' : IDL.Func([], [IDL.Bool], ['query']),
  'verifyUser' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TradingMode = IDL.Variant({
    'liveTrading' : IDL.Null,
    'shadowTrading' : IDL.Null,
    'paperTrading' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PromptTemplate = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'example' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const PositionType = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const Trade = IDL.Record({
    'owner' : IDL.Principal,
    'size' : IDL.Float64,
    'profitLoss' : IDL.Float64,
    'positionType' : PositionType,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Opt(IDL.Float64),
  });
  const TradingStatus = IDL.Record({
    'mode' : TradingMode,
    'tradingEnabled' : IDL.Bool,
    'binanceConnected' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'tradingStatus' : TradingStatus,
  });
  const CandleSummary = IDL.Record({
    'totalVolume' : IDL.Float64,
    'totalCount' : IDL.Int,
    'avgPrice' : IDL.Float64,
    'avgVolume' : IDL.Float64,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'time' : IDL.Int,
    'volume' : IDL.Float64,
  });
  const Dataset = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'candles' : IDL.Vec(Candle),
    'uploadedAt' : IDL.Int,
  });
  const HealthStatus = IDL.Variant({
    'healthy' : IDL.Null,
    'unreachable' : IDL.Null,
    'maintenance' : IDL.Null,
    'degraded' : IDL.Null,
    'appIssue' : IDL.Null,
  });
  const AppHealth = IDL.Record({
    'status' : HealthStatus,
    'message' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBinanceAccount' : IDL.Func([IDL.Text, IDL.Text, TradingMode], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'disconnectBinance' : IDL.Func([], [], []),
    'filterPromptTemplates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PromptTemplate)],
        ['query'],
      ),
    'getAllDatasetIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllPromptTemplates' : IDL.Func(
        [],
        [IDL.Vec(PromptTemplate)],
        ['query'],
      ),
    'getAllTrades' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandleSummary' : IDL.Func([IDL.Text], [CandleSummary], ['query']),
    'getDataset' : IDL.Func([IDL.Text], [IDL.Opt(Dataset)], ['query']),
    'getHealthStatus' : IDL.Func([], [HealthStatus], ['query']),
    'getPromptTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PromptTemplate)],
        ['query'],
      ),
    'getSystemHealth' : IDL.Func([], [AppHealth], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePromptTemplate' : IDL.Func([PromptTemplate], [], []),
    'saveTrade' : IDL.Func([IDL.Text, Trade], [], []),
    'setSystemHealth' : IDL.Func([HealthStatus], [], []),
    'updateTradingMode' : IDL.Func([TradingMode], [], []),
    'uploadDataset' : IDL.Func(
        [IDL.Text, IDL.Vec(Candle), IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'uploadFile' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'verifyBinanceConnection' : IDL.Func([], [IDL.Bool], ['query']),
    'verifyUser' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };