/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppHealth {
  'status' : HealthStatus,
  'message' : [] | [string],
}
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'time' : bigint,
  'volume' : number,
}
export interface CandleSummary {
  'totalVolume' : number,
  'totalCount' : bigint,
  'avgPrice' : number,
  'avgVolume' : number,
}
export interface Dataset {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'description' : [] | [string],
  'candles' : Array<Candle>,
  'uploadedAt' : bigint,
}
export type ExternalBlob = Uint8Array;
export type HealthStatus = { 'healthy' : null } |
  { 'unreachable' : null } |
  { 'maintenance' : null } |
  { 'degraded' : null } |
  { 'appIssue' : null };
export type PositionType = { 'long' : null } |
  { 'short' : null };
export interface PromptTemplate {
  'id' : string,
  'content' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'example' : [] | [string],
  'category' : string,
}
export interface Trade {
  'owner' : Principal,
  'size' : number,
  'profitLoss' : number,
  'positionType' : PositionType,
  'entryPrice' : number,
  'exitPrice' : [] | [number],
}
export type TradingMode = { 'liveTrading' : null } |
  { 'shadowTrading' : null } |
  { 'paperTrading' : null };
export interface TradingStatus {
  'mode' : TradingMode,
  'tradingEnabled' : boolean,
  'binanceConnected' : boolean,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'tradingStatus' : TradingStatus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBinanceAccount' : ActorMethod<[string, string, TradingMode], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'disconnectBinance' : ActorMethod<[], undefined>,
  'filterPromptTemplates' : ActorMethod<[string], Array<PromptTemplate>>,
  'getAllDatasetIds' : ActorMethod<[], Array<string>>,
  'getAllPromptTemplates' : ActorMethod<[], Array<PromptTemplate>>,
  'getAllTrades' : ActorMethod<[string], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandleSummary' : ActorMethod<[string], CandleSummary>,
  'getDataset' : ActorMethod<[string], [] | [Dataset]>,
  'getHealthStatus' : ActorMethod<[], HealthStatus>,
  'getPromptTemplate' : ActorMethod<[string], [] | [PromptTemplate]>,
  'getSystemHealth' : ActorMethod<[], AppHealth>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePromptTemplate' : ActorMethod<[PromptTemplate], undefined>,
  'saveTrade' : ActorMethod<[string, Trade], undefined>,
  'setSystemHealth' : ActorMethod<[HealthStatus], undefined>,
  'updateTradingMode' : ActorMethod<[TradingMode], undefined>,
  'uploadDataset' : ActorMethod<
    [string, Array<Candle>, string, [] | [string]],
    undefined
  >,
  'uploadFile' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'verifyBinanceConnection' : ActorMethod<[], boolean>,
  'verifyUser' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];