/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CandleSummary {
    totalVolume: number;
    totalCount: bigint;
    avgPrice: number;
    avgVolume: number;
}
export interface PromptTemplate {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    example?: string;
    category: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trade {
    owner: Principal;
    size: number;
    profitLoss: number;
    positionType: PositionType;
    entryPrice: number;
    exitPrice?: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Dataset {
    id: string;
    owner: Principal;
    name: string;
    description?: string;
    candles: Array<Candle>;
    uploadedAt: bigint;
}
export interface TradingStatus {
    mode: TradingMode;
    tradingEnabled: boolean;
    binanceConnected: boolean;
}
export interface Candle {
    low: number;
    high: number;
    close: number;
    open: number;
    time: bigint;
    volume: number;
}
export interface AppHealth {
    status: HealthStatus;
    message?: string;
}
export interface UserProfile {
    name: string;
    createdAt: bigint;
    email?: string;
    tradingStatus: TradingStatus;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum HealthStatus {
    healthy = "healthy",
    unreachable = "unreachable",
    maintenance = "maintenance",
    degraded = "degraded",
    appIssue = "appIssue"
}
export enum PositionType {
    long_ = "long",
    short_ = "short"
}
export enum TradingMode {
    liveTrading = "liveTrading",
    shadowTrading = "shadowTrading",
    paperTrading = "paperTrading"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBinanceAccount(apiKey: string, secretKey: string, mode: TradingMode): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    disconnectBinance(): Promise<void>;
    filterPromptTemplates(category: string): Promise<Array<PromptTemplate>>;
    getAllDatasetIds(): Promise<Array<string>>;
    getAllPromptTemplates(): Promise<Array<PromptTemplate>>;
    getAllTrades(tradeId: string): Promise<Array<Trade>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandleSummary(datasetId: string): Promise<CandleSummary>;
    getDataset(datasetId: string): Promise<Dataset | null>;
    getHealthStatus(): Promise<HealthStatus>;
    getPromptTemplate(id: string): Promise<PromptTemplate | null>;
    getSystemHealth(): Promise<AppHealth>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePromptTemplate(template: PromptTemplate): Promise<void>;
    saveTrade(tradeId: string, trade: Trade): Promise<void>;
    setSystemHealth(state: HealthStatus): Promise<void>;
    updateTradingMode(mode: TradingMode): Promise<void>;
    uploadDataset(datasetId: string, candles: Array<Candle>, name: string, desc: string | null): Promise<void>;
    uploadFile(blob: ExternalBlob): Promise<ExternalBlob>;
    verifyBinanceConnection(): Promise<boolean>;
    verifyUser(): Promise<boolean>;
}
import type { AppHealth as _AppHealth, Candle as _Candle, Dataset as _Dataset, ExternalBlob as _ExternalBlob, HealthStatus as _HealthStatus, PositionType as _PositionType, PromptTemplate as _PromptTemplate, Trade as _Trade, TradingMode as _TradingMode, TradingStatus as _TradingStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBinanceAccount(arg0: string, arg1: string, arg2: TradingMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBinanceAccount(arg0, arg1, to_candid_TradingMode_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBinanceAccount(arg0, arg1, to_candid_TradingMode_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async disconnectBinance(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectBinance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectBinance();
            return result;
        }
    }
    async filterPromptTemplates(arg0: string): Promise<Array<PromptTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPromptTemplates(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPromptTemplates(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDatasetIds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDatasetIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDatasetIds();
            return result;
        }
    }
    async getAllPromptTemplates(): Promise<Array<PromptTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPromptTemplates();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPromptTemplates();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrades(arg0: string): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandleSummary(arg0: string): Promise<CandleSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandleSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandleSummary(arg0);
            return result;
        }
    }
    async getDataset(arg0: string): Promise<Dataset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataset(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataset(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthStatus(): Promise<HealthStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthStatus();
                return from_candid_HealthStatus_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthStatus();
            return from_candid_HealthStatus_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromptTemplate(arg0: string): Promise<PromptTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptTemplate(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptTemplate(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemHealth(): Promise<AppHealth> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemHealth();
                return from_candid_AppHealth_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemHealth();
            return from_candid_AppHealth_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async savePromptTemplate(arg0: PromptTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePromptTemplate(to_candid_PromptTemplate_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePromptTemplate(to_candid_PromptTemplate_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveTrade(arg0: string, arg1: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTrade(arg0, to_candid_Trade_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTrade(arg0, to_candid_Trade_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setSystemHealth(arg0: HealthStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSystemHealth(to_candid_HealthStatus_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSystemHealth(to_candid_HealthStatus_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTradingMode(arg0: TradingMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTradingMode(to_candid_TradingMode_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTradingMode(to_candid_TradingMode_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadDataset(arg0: string, arg1: Array<Candle>, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDataset(arg0, arg1, arg2, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDataset(arg0, arg1, arg2, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async uploadFile(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(await to_candid_ExternalBlob_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(await to_candid_ExternalBlob_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyBinanceConnection(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyBinanceConnection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyBinanceConnection();
            return result;
        }
    }
    async verifyUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUser();
            return result;
        }
    }
}
function from_candid_AppHealth_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppHealth): AppHealth {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Dataset_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dataset): Dataset {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HealthStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PositionType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionType): PositionType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PromptTemplate_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromptTemplate): PromptTemplate {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TradingMode_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingMode): TradingMode {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TradingStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingStatus): TradingStatus {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dataset]): Dataset | null {
    return value.length === 0 ? null : from_candid_Dataset_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PromptTemplate]): PromptTemplate | null {
    return value.length === 0 ? null : from_candid_PromptTemplate_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    example: [] | [string];
    category: string;
}): {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    example?: string;
    category: string;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        example: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.example)),
        category: value.category
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    size: number;
    profitLoss: number;
    positionType: _PositionType;
    entryPrice: number;
    exitPrice: [] | [number];
}): {
    owner: Principal;
    size: number;
    profitLoss: number;
    positionType: PositionType;
    entryPrice: number;
    exitPrice?: number;
} {
    return {
        owner: value.owner,
        size: value.size,
        profitLoss: value.profitLoss,
        positionType: from_candid_PositionType_n19(_uploadFile, _downloadFile, value.positionType),
        entryPrice: value.entryPrice,
        exitPrice: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.exitPrice))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: bigint;
    email: [] | [string];
    tradingStatus: _TradingStatus;
}): {
    name: string;
    createdAt: bigint;
    email?: string;
    tradingStatus: TradingStatus;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.email)),
        tradingStatus: from_candid_TradingStatus_n25(_uploadFile, _downloadFile, value.tradingStatus)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mode: _TradingMode;
    tradingEnabled: boolean;
    binanceConnected: boolean;
}): {
    mode: TradingMode;
    tradingEnabled: boolean;
    binanceConnected: boolean;
} {
    return {
        mode: from_candid_TradingMode_n27(_uploadFile, _downloadFile, value.mode),
        tradingEnabled: value.tradingEnabled,
        binanceConnected: value.binanceConnected
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    name: string;
    description: [] | [string];
    candles: Array<_Candle>;
    uploadedAt: bigint;
}): {
    id: string;
    owner: Principal;
    name: string;
    description?: string;
    candles: Array<Candle>;
    uploadedAt: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.description)),
        candles: value.candles,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _HealthStatus;
    message: [] | [string];
}): {
    status: HealthStatus;
    message?: string;
} {
    return {
        status: from_candid_HealthStatus_n34(_uploadFile, _downloadFile, value.status),
        message: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.message))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): PositionType {
    return "long" in value ? PositionType.long : "short" in value ? PositionType.short : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    liveTrading: null;
} | {
    shadowTrading: null;
} | {
    paperTrading: null;
}): TradingMode {
    return "liveTrading" in value ? TradingMode.liveTrading : "shadowTrading" in value ? TradingMode.shadowTrading : "paperTrading" in value ? TradingMode.paperTrading : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthy: null;
} | {
    unreachable: null;
} | {
    maintenance: null;
} | {
    degraded: null;
} | {
    appIssue: null;
}): HealthStatus {
    return "healthy" in value ? HealthStatus.healthy : "unreachable" in value ? HealthStatus.unreachable : "maintenance" in value ? HealthStatus.maintenance : "degraded" in value ? HealthStatus.degraded : "appIssue" in value ? HealthStatus.appIssue : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PromptTemplate>): Array<PromptTemplate> {
    return value.map((x)=>from_candid_PromptTemplate_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n17(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HealthStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthStatus): _HealthStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PositionType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionType): _PositionType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_PromptTemplate_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromptTemplate): _PromptTemplate {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_TradingMode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingMode): _TradingMode {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TradingStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingStatus): _TradingStatus {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: bigint;
    email?: string;
    tradingStatus: TradingStatus;
}): {
    name: string;
    createdAt: bigint;
    email: [] | [string];
    tradingStatus: _TradingStatus;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: value.email ? candid_some(value.email) : candid_none(),
        tradingStatus: to_candid_TradingStatus_n41(_uploadFile, _downloadFile, value.tradingStatus)
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mode: TradingMode;
    tradingEnabled: boolean;
    binanceConnected: boolean;
}): {
    mode: _TradingMode;
    tradingEnabled: boolean;
    binanceConnected: boolean;
} {
    return {
        mode: to_candid_TradingMode_n8(_uploadFile, _downloadFile, value.mode),
        tradingEnabled: value.tradingEnabled,
        binanceConnected: value.binanceConnected
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    example?: string;
    category: string;
}): {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    example: [] | [string];
    category: string;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        example: value.example ? candid_some(value.example) : candid_none(),
        category: value.category
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    size: number;
    profitLoss: number;
    positionType: PositionType;
    entryPrice: number;
    exitPrice?: number;
}): {
    owner: Principal;
    size: number;
    profitLoss: number;
    positionType: _PositionType;
    entryPrice: number;
    exitPrice: [] | [number];
} {
    return {
        owner: value.owner,
        size: value.size,
        profitLoss: value.profitLoss,
        positionType: to_candid_PositionType_n47(_uploadFile, _downloadFile, value.positionType),
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionType): {
    long: null;
} | {
    short: null;
} {
    return value == PositionType.long ? {
        long_: null
    } : value == PositionType.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthStatus): {
    healthy: null;
} | {
    unreachable: null;
} | {
    maintenance: null;
} | {
    degraded: null;
} | {
    appIssue: null;
} {
    return value == HealthStatus.healthy ? {
        healthy: null
    } : value == HealthStatus.unreachable ? {
        unreachable: null
    } : value == HealthStatus.maintenance ? {
        maintenance: null
    } : value == HealthStatus.degraded ? {
        degraded: null
    } : value == HealthStatus.appIssue ? {
        appIssue: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingMode): {
    liveTrading: null;
} | {
    shadowTrading: null;
} | {
    paperTrading: null;
} {
    return value == TradingMode.liveTrading ? {
        liveTrading: null
    } : value == TradingMode.shadowTrading ? {
        shadowTrading: null
    } : value == TradingMode.paperTrading ? {
        paperTrading: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
